# Generated by Django 5.2.1 on 2026-03-18 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mediaitem',
            options={'ordering': ['order', '-uploaded_at']},
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
